# this workflow validates the PR names for the `develop` branch
name: 'Release development packages as @next'

on:
  push:
    branches:
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # This only caches ~/.npm, therefore each subsequent
          # job needs to run `npm ci` to install deps from npm cache
          # alternative is to cache `node_modules` directly
          # TODO:
          # https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
          # Add caching of `node_modules` to speed up this workflow
          cache: npm

      # install dependencies from the package-lock.json
      - name: Install dependencies
        run: npm ci

  # releases all packages
  release:
    runs-on: ubuntu-latest
    needs: install
    steps:
      # check out the repository
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Build'
        run: npm run build

      - name: 'Version and publish'
        env:
          # GITHUB_TOKEN was necessary for access to some PR data
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish -- --dist-tag next
